# Docker compose file for multi-container quiz-2015 app
#
# Federico A. Fernández Moreno
# Rodrigo Barbado Esteban

tracks.cdpsfy.es:
  build: tracks
  ports:
    - "8000:8000"

server:
  build: server
  ports:
    - "8080:8080"
  links:
    - tracks.cdpsfy.es
  environment:
    - TRACKS_HOST=tracks.cdpsfy.es:8000