# Docker compose file for multi-container cdpsfy app
#
# Federico A. Fernández Moreno
# Rodrigo Barbado Esteban

# tracks.cdpsfy.es servers and NAS pool
nas:
  image: ubuntu
  volume_driver: flocker
  volumes:
    - nas:/mnt/nas

s1:
  build: tracks
  volumes_from:
    - nas
  environment:
    - PORT=3000
    - NASPATH=/mnt/nas
    - TMPPATH=/mnt/nas/.tmp

s2:
  build: tracks
  volumes_from:
    - nas
  environment:
    - PORT=3000
    - NASPATH=/mnt/nas
    - TMPPATH=/mnt/nas/.tmp

s3:
  build: tracks
  volumes_from:
    - nas
  environment:
    - PORT=3000
    - NASPATH=/mnt/nas
    - TMPPATH=/mnt/nas/.tmp

s4:
  build: tracks
  volumes_from:
    - nas
  environment:
    - PORT=3000
    - NASPATH=/mnt/nas
    - TMPPATH=/mnt/nas/.tmp

# load balancer
tracks.cdpsfy.es:
  build: lb
  ports:
    - "8000:80"
    - "8001:8001"
  links:
    - s1
    - s2
    - s3
    - s4

# server.cdpsfy.es
db:
  image: postgres
  volume_driver: flocker
  volumes:
    - dbdata:/var/lib/postgresql/data/cdpsfy
  environment:
    - POSTGRES_PASSWORD=mipasswordsecreta
    - PGDATA=/var/lib/postgresql/data/cdpsfy

www:
  build: server
  ports:
    - "80:3000"
  links:
    - tracks.cdpsfy.es
    - db
  environment:
    - TRACKS_HOST=tracks.cdpsfy.es
    - PORT=3000
    - DATABASE_URL=postgres://postgres:mipasswordsecreta@db:5432/postgres
    - PASSWORD_ENCRYPTION_KEY=misecreto

# nagios monitoring server
nagios:
  build: nagios
  ports:
    - "8003:80"
  links:
    - s1
    - s2
    - s3
    - s4
    - tracks.cdpsfy.es
    - www