# Docker compose file for multi-container cdpsfy app
#
# Federico A. Fernández Moreno
# Rodrigo Barbado Esteban

# tracks.cdpsfy.es servers and NAS pool
nas:
  image: ubuntu
  volume_driver: flocker
  volumes:
    - nas:/mnt/nas
  command: tail -f /dev/null

tracks:
  build: tracks
  volumes_from:
    - nas
  expose:
    - "5000"
  environment:
    - PORT=5000
    - NASPATH=/mnt/nas
    - TMPPATH=/mnt/nas/.tmp/
    - TCP_PORTS=5000

lb1:
  image: tutum/haproxy
  container_name: tracks.cdpsfy.es
  links:
    - tracks
  ports:
   - "5000:5000"
  environment:
   - BALANCE=roundrobin
   - MODE=tcp

# server.cdpsfy.es
db:
  image: postgres
  container_name: db
  volume_driver: flocker
  volumes:
    - dbdata:/var/lib/postgresql/data/cdpsfy
  environment:
    - POSTGRES_PASSWORD=mipasswordsecreta
    - PGDATA=/var/lib/postgresql/data/cdpsfy

lb2:
  image: tutum/haproxy
  container_name: www.cdpsfy.es
  links:
    - www
  ports:
   - "80:5000"
  environment:
   - BALANCE=first
   - MODE=tcp

www:
  build: server
  expose:
    - "5000"
  links:
    - db
    - lb1
  environment:
    - TRACKS_HOST=tracks.cdpsfy.es:5000
    - PORT=5000
    - DATABASE_URL=postgres://postgres:mipasswordsecreta@db:5432/postgres
    - PASSWORD_ENCRYPTION_KEY=misecreto
    - TCP_PORTS=5000

# nagios monitoring server
nagios:
  build: nagios
  links:
    - nas
    - tracks
    - www
    - lb1
    - lb2
    - db
  ports:
    - "8003:80"